[vision]
enable = true
stream_interval = 0.2
profile = "object"
threshold = 0.5
model_path = "models/default.pt"
log = true     # vision-specific logging

[movement]
enable = true
log = false

[voice]
enable = true
log = false

[led]
enable = true
log = false

[hearing]
enable = true
log = false

[logging]
level = "INFO" # global log level
