[vision]
enable = true
stream_interval = 0.2
profile = "object"
threshold = 0.5
model_path = "models/default.pt"

[movement]
enable = true

[voice]
enable = true

[led]
enable = true

[hearing]
enable = true

[logging]
enable = true
level = "INFO" # global log level
vision = true
movement = false
voice = false
led = false
hearing = false
