"""Shared default values and thresholds for vision modules."""

# Vision interface defaults
CAMERA_RESOLUTION = (640, 480)
REF_SIZE = (160, 120)
BLUR_KERNEL = 5
BORDER_MARGIN = 6

# API thresholds
DEFAULT_STABLE = True
DEFAULT_ON_THRESHOLD = 0.55
DEFAULT_OFF_THRESHOLD = 0.45
DEFAULT_STICK_K = 5
DEFAULT_MISS_M = 8
DEFAULT_ROI_FACTOR = 1.8
DEFAULT_EMA_ALPHA = 0.7

# Dynamic adjuster defaults
CANNY_T1_INIT = 50.0
CANNY_T2_RATIO = 2.5
CANNY_LIFE_MIN = 5.0
CANNY_LIFE_MAX = 10.0
CANNY_RESCUE_LIFE_MIN = 3.0
CANNY_KP = 4.0
CANNY_MAX_ITER = 25
ADAPTIVE_BLOCK_SIZE = 11
ADAPTIVE_C = 2

# Contour detector defaults
MORPH_CLOSE_MIN = 3
MORPH_CLOSE_MAX = 21
MORPH_DIL_MIN = 3
MORPH_DIL_MAX = 15
MORPH_STEPS = 10

GEO_AR_MIN = 0.40
GEO_AR_MAX = 2.20
GEO_BBOX_HARD_CAP = 0.50
GEO_BBOX_MIN = 0.18
GEO_BBOX_MAX = 0.35
GEO_FILL_MIN = 0.60
GEO_FILL_MAX = 0.95
GEO_MIN_AREA_FRAC = 0.03

WEIGHT_AREA = 0.35
WEIGHT_FILL = 0.15
WEIGHT_SOLIDITY = 0.20
WEIGHT_CIRCULAR = 0.10
WEIGHT_RECT = 0.15
WEIGHT_AR = 0.10
WEIGHT_CENTER_BIAS = 0.25
WEIGHT_DIST = 0.20

PREMORPH_BOTTOM_MARGIN_PCT = 20
PREMORPH_MIN_BLOB_PX = 100
PREMORPH_FILL_FROM_EDGES = True
BOTTOM_MARGIN_MAX = 40

COLORGATE_ENABLED = False
COLORGATE_MODE = "lab_bg"
COLORGATE_AB_THRESH = 22
COLORGATE_HSV_LO = (5, 80, 40)
COLORGATE_HSV_HI = (30, 255, 255)
COLORGATE_COMBINE = "OR"
COLORGATE_MIN_COVER_PCT = 0.5
COLORGATE_MAX_COVER_PCT = 60.0
